[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[project]
name = "bandits"
requires-python = ">3.10"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest", "coverage"]
